// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedeConcessionarias.Models;

#nullable disable

namespace RedeConcessionarias.Migrations
{
    [DbContext(typeof(RedeConcessionariaContext))]
    [Migration("20220205012136_AlteraDb")]
    partial class AlteraDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RedeConcessionarias.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"), 1L, 1);

                    b.Property<int>("CEPCLliente")
                        .HasColumnType("int");

                    b.Property<string>("CadastroCliente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EnderecoClienteBairro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EnderecoClienteCidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EnderecoClienteComplemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoClienteLogradouro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("EnderecoClienteNumero")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeiculo"), 1L, 1);

                    b.Property<string>("AcessoriosVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnoVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("ChassiVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KmVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("ModeloVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorVeiculo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VersaoSistVeiculo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdVeiculo");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Venda", b =>
                {
                    b.Property<int>("IdVendas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendas"), 1L, 1);

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdClienteNavigationIdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("IdVeiculoNavigationIdVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaVendedor")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaVendedorNavigationMatriculaVendedor")
                        .HasColumnType("int");

                    b.HasKey("IdVendas");

                    b.HasIndex("IdClienteNavigationIdCliente");

                    b.HasIndex("IdVeiculoNavigationIdVeiculo");

                    b.HasIndex("MatriculaVendedorNavigationMatriculaVendedor");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Vendedor", b =>
                {
                    b.Property<int>("MatriculaVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatriculaVendedor"), 1L, 1);

                    b.Property<DateTime>("AdmissaoVendedor")
                        .HasColumnType("datetime2");

                    b.Property<string>("CpfVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalarioVendedor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelefoneVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendasMesVendedor")
                        .HasColumnType("int");

                    b.Property<int>("VendasTotalVendedor")
                        .HasColumnType("int");

                    b.HasKey("MatriculaVendedor");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Venda", b =>
                {
                    b.HasOne("RedeConcessionarias.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Venda")
                        .HasForeignKey("IdClienteNavigationIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedeConcessionarias.Models.Veiculo", "IdVeiculoNavigation")
                        .WithMany("Venda")
                        .HasForeignKey("IdVeiculoNavigationIdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedeConcessionarias.Models.Vendedor", "MatriculaVendedorNavigation")
                        .WithMany("Vendas")
                        .HasForeignKey("MatriculaVendedorNavigationMatriculaVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdVeiculoNavigation");

                    b.Navigation("MatriculaVendedorNavigation");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Cliente", b =>
                {
                    b.Navigation("Venda");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Veiculo", b =>
                {
                    b.Navigation("Venda");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Vendedor", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
