// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedeConcessionarias.Models;

#nullable disable

namespace RedeConcessionarias.Migrations
{
    [DbContext(typeof(RedeConcessionariaContext))]
    partial class RedeConcessionariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RedeConcessionarias.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"), 1L, 1);

                    b.Property<string>("CadastroCliente")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoClienteBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoClienteCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoClienteComplemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoClienteLogradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnderecoClienteNumero")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Veiculo", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeiculoId"), 1L, 1);

                    b.Property<string>("AcessoriosVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnoVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("ChassiVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KmVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("ModeloVeiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorVeiculo")
                        .HasColumnType("float");

                    b.Property<decimal>("VersaoSistVeiculo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VeiculoId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Venda", b =>
                {
                    b.Property<int>("VendasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendasId"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<double>("ValorVenda")
                        .HasColumnType("float");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("VendasId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Vendedor", b =>
                {
                    b.Property<int>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedorId"), 1L, 1);

                    b.Property<DateTime>("AdmissaoVendedor")
                        .HasColumnType("datetime2");

                    b.Property<double>("BonusDestaqueVendedor")
                        .HasColumnType("float");

                    b.Property<string>("CpfVendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestaqueVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailVendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeVendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalarioVendedor")
                        .HasColumnType("float");

                    b.Property<string>("TelefoneVendedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VendasMesVendedor")
                        .HasColumnType("float");

                    b.HasKey("VendedorId");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Venda", b =>
                {
                    b.HasOne("RedeConcessionarias.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedeConcessionarias.Models.Veiculo", "Veiculo")
                        .WithMany("Vendas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedeConcessionarias.Models.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Veiculo", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("RedeConcessionarias.Models.Vendedor", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
